/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import domain.Cars;
import file.CarsFile;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author faubricioch
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        insertCar = new javax.swing.JMenuItem();
        showCars = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        exitOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Ingreso de datos");

        insertCar.setText("Insertar, actualiza o eliminar auto");
        insertCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCarActionPerformed(evt);
            }
        });
        jMenu1.add(insertCar);

        showCars.setText("Mostrar todos los autos");
        showCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCarsActionPerformed(evt);
            }
        });
        jMenu1.add(showCars);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        exitOption.setText("Salir");
        exitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitOptionActionPerformed(evt);
            }
        });
        jMenu2.add(exitOption);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCarActionPerformed
        InsertCars inCar=new InsertCars();
        inCar.setVisible(true);
    }//GEN-LAST:event_insertCarActionPerformed

    private void exitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitOptionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitOptionActionPerformed

    private void showCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCarsActionPerformed
        try {
            File fileCar=new File("./Cars.dat");
            CarsFile carFile=new CarsFile(fileCar);
            showCars shCar=new showCars();
            shCar.setVisible(true);
            //cantidad de elementos de ArrayList
            int arraySize=carFile.getAllCars().size();
            ArrayList<Cars> carsArray=carFile.getAllCars();
            String text="";
            //recorrido del array
            //
            for(int i=0; i<arraySize;i++){
                text="Nombre: "+carsArray.get(i).getName()+
                        "\nAño: "+carsArray.get(i).getYear()+
                        "\nKilometraje: "+carsArray.get(i).getMileage()+
                        "\nAmericano: "+carsArray.get(i).isAmerican()+
                        "\nSerie: "+carsArray.get(i).getSerie()+"\n";
                shCar.jTextArea1.setText(shCar.jTextArea1.getText()+"\n"+text);
            }
            shCar.jTextArea1.setEditable(false);
            
        } catch (IOException ex) {
            Logger.getLogger(MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showCarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitOption;
    private javax.swing.JMenuItem insertCar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem showCars;
    // End of variables declaration//GEN-END:variables
}
